name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  camera_android:
    # When depending on this package from a real application you should use:
    #   camera_android: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  camera_platform_interface:
    path: ../../camera_platform_interface
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  video_player: ^2.7.0
  opencv_core: ^1.4.3
  sensors_plus: ^5.0.0
  screenshot: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

hooks:
  user_defines:
    dartcv4:
      exclude_modules:
        - contrib
        - dnn
        - features2d
        - core
      include_modules:
        - core
        - imgproc
