name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  camera:
    path: ../
  flutter:
    sdk: flutter
  image: ^4.5.4
  path_provider: ^2.0.0
  pdf_combiner: ^4.4.0
  pdfx: ^2.9.2
  screenshot: ^3.0.0
  sensors_plus: ^7.0.0
  video_player: ^2.7.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

flutter:
  uses-material-design: true
